---
title: "Checkpoint 4"
author: "Camilla Bendetti, Rock Pang, Jane Roarty"
date: "4/30/2020"
output: html_document
runtime: shiny
---

```{r, echo=FALSE}
library(shinydashboard)
library(shiny)
library(bayesrules)  # for the plotting functions
library(ggplot2)
```

```{r, echo=FALSE}
header <- dashboardHeader(title = "Covid-19 Symptom Checker", titleWidth = 300)
```

```{r, echo=FALSE}
sidebar <- dashboardSidebar(
  ## Sidebar content
    dashboardSidebar(
      sidebarMenu(
         menuItem("Welcome", tabName = "welcome", icon = icon("info")),  
        menuItem("Symptoms", tabName = "symptoms", icon = icon("thermometer-three-quarters")),
        menuItem("Covid Probabilities", tabName = "covidprobs", icon = icon("dashboard")),
        menuItem("Flu Probabilities", tabName = "fluprobs", icon = icon("dashboard")),
        menuItem("Neither Probabilities", tabName = "symptomprobs", icon = icon("dashboard")),
        menuItem("Results", tabName = "results", icon = icon("poll-h")),
        menuItem("Theory", tabName = "theory", icon = icon("info"))
        )
      )
)

```

```{r, echo=FALSE}

body <- dashboardBody(tabItems(
  
  tabItem(tabName = "welcome", 
          tags$h2("Welcome to a Naive Bayesian Model for COVID-19"),
          tags$h3("Welcome to a Naive Bayesian Model for COVID-19. In this SHINY app, there are two main features. In the symptoms tab you can check the box of which symptoms you are experiencing. The results tab will then tell you the probability that you have COVID-19, the probability that you have the flu, and the probability that you have neither. In the 'Probabilities' tabs you can adjust the probabilities for each symptom. We made assumptions about default probabilities using data from the CDC(link) and (link)."),
          tags$h4("NOTICE: This app should not be used for diagnosis. Many assumptions were made in the creation of this app. If you think that you have coronavirus, you should get tested immediately and stay quarantined until you are recovered.")),
  
  
  
  #First tab content
  tabItem(tabName = "symptoms",
            fluidRow(
              box(
                checkboxInput(inputId = "isFever", 
                              label = "Fever",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isDryCough", 
                              label = "Dry Cough",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isFatigue", 
                              label = "Fatigue",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isShortBreath", 
                              label = "Shortness of Breath",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isSoreThroat", 
                              label = "Sore Throat",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isHeadache", 
                              label = "Headache",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isChills", 
                              label = "Chills",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isNausea", 
                              label = "Nausea",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isCongestion", 
                              label = "Congestion",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isDiarrhea", 
                              label = "Diarrhea",
                              value = FALSE)
              ), 
              box(
                checkboxInput(inputId = "isJointAche", 
                              label = "Joint Ache",
                              value = FALSE)
              )
            )
          ),
  
  # Second tab content
  tabItem(tabName = "covidprobs",
          fluidRow(
            box(
              title = "Symptoms",
              sliderInput(inputId = "c1", 
                          label = "Fever:", 
                          min = 0, 
                          max = 1, 
                          value = 0.879, 
                          step = 0.001),
              sliderInput(inputId = "c2", 
                          label = "Dry Cough:", 
                          min = 0, 
                          max = 1, 
                          value = 0.677, 
                          step = 0.001),
              sliderInput(inputId = "c3", 
                          label = "Fatigue", 
                          min = 0, 
                          max = 1, 
                          value = 0.381, 
                          step = 0.001),
              sliderInput(inputId = "c4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.186, 
                          step = 0.001),
              sliderInput(inputId = "c5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.139, 
                          step = 0.001),
              sliderInput(inputId = "c6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.136, 
                          step = 0.001),
              sliderInput(inputId = "c7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.114, 
                          step = 0.001),
              sliderInput(inputId = "c8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
              sliderInput(inputId = "c9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.048, 
                          step = 0.001),
              sliderInput(inputId = "c10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.037, 
                          step = 0.001)
              )
            )
          ),
  
  #third tab
  tabItem(tabName = "fluprobs",
    fluidRow(
      box(
          sliderInput(inputId = "f1", 
                          label = "Fever:", 
                          min = 0, 
                          max = 1, 
                          value = 0.68, 
                          step = 0.001),
          sliderInput(inputId = "f2", 
                          label = "Dry Cough:", 
                          min = 0, 
                          max = 1, 
                          value = 0.93, 
                          step = 0.001),
          sliderInput(inputId = "f3", 
                          label = "Fatigue", 
                          min = 0, 
                          max = 1, 
                          value = 0.94, 
                          step = 0.001),
          sliderInput(inputId = "f4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001),
          sliderInput(inputId = "f5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001),
               sliderInput(inputId = "f6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001),
               sliderInput(inputId = "f7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.5, 
                          step = 0.001),
               sliderInput(inputId = "f8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001),
               sliderInput(inputId = "f9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.5, 
                          step = 0.001),
               sliderInput(inputId = "f10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    )
  )
  ),
  
  #fourth tab
  tabItem(tabName = "symptomprobs",
    fluidRow(
        box(
          sliderInput(inputId = "s1", 
                          label = "Fever:", 
                          min = 0, 
                          max = 1, 
                          value = 0.03, 
                          step = 0.001),
          sliderInput(inputId = "s2", 
                          label = "Dry Cough:", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
          sliderInput(inputId = "s3", 
                          label = "Fatigue", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001),
          sliderInput(inputId = "s4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.03, 
                          step = 0.001),
          sliderInput(inputId = "s5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
          sliderInput(inputId = "s6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001),
               sliderInput(inputId = "s7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.01, 
                          step = 0.001),
               sliderInput(inputId = "s8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
               sliderInput(inputId = "s9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
               sliderInput(inputId = "s10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.01, 
                          step = 0.001)
    )
)
),
  
  tabItem(tabName = "results",
    fluidRow(
      box(
                title = "Results",
                tableOutput("priorTable"),
                h3("Probability of covid-19 = ", textOutput("result", container = span))
                )
    )
  )
  
  ))

```


```{r}
ui <- dashboardPage(header, sidebar, body)


server <- function(input, output) {
  
  bools <- reactive({
      c(input$isFever, input$isDryCough, input$isFatigue, input$isShortBreath, input$isSoreThroat, input$isHeadache, input$isChills, input$isNausea, input$isCongestion, input$isDiarrhea)
    })
  
  x <- reactive({
    c(input$s1, input$s2, input$s3, input$s4, input$s5, input$s6, input$s7, input$s8, input$s9, input$s10)
  })
  
  output$priorTable <- renderTable({
    # Figure out how to make the table wrap around on a smaller window
    df <- data.frame(S1 = c(input$c1, input$f1, input$s1),
                   S2 = c(input$c2, input$f2, input$s2),
                   S3 = c(input$c3, input$f3, input$s3),
                   S4 = c(input$c4, input$f4, input$s4),
                   S5 = c(input$c5, input$f5, input$s5),
                   S6 = c(input$c6, input$f6, input$s6),
                   S7 = c(input$c7, input$f7, input$s7),
                   S8 = c(input$c8, input$f8, input$s8),
                   S9 = c(input$c9, input$f9, input$s9),
                   S10 = c(input$c10, input$f10, input$s10)
                   )
    df
  })
  
  output$result <- renderText({
    c_prop <- (input$c1 * input$c2 * input$c3 * input$c4 * input$c5 * input$c6 * input$c7 * input$c8 * input$c9 * input$c10 * 0.002)
    f_prop <- (input$f1 * input$f2 * input$f3 * input$f4 * input$f5 * input$f6 * input$f7 * input$f8 * input$f9 * input$f10 * 0.01)
    n_prop <- (input$s1 * input$s2 * input$s3 * input$s4 * input$s5 * input$s6 * input$s7 * input$s8 * input$s9 * input$s10 * 0.988)
    covid <- c_prop/(c_prop+f_prop+n_prop)
    flu <- f_prop/(c_prop+f_prop+n_prop)
    neither <- n_prop/(c_prop+f_prop+n_prop)
    c(covid, flu, neither)
  })
}

output$feverslider  <- renderUI({
    if(bools()[1]) {
      sliderInput(inputId = "s1", 
                            label = "Fever:", 
                            min = 0, 
                            max = 1, 
                            value = 0.879, 
                            step = 0.001)
    }
  })
  
  output$dryCoughSlider <- renderUI({
    if(bools()[2]) {
      sliderInput(inputId = "s2", 
                            label = "Dry Cough:", 
                            min = 0, 
                            max = 1, 
                            value = 0.677, 
                            step = 0.001)
    }
  })
  
  output$fatigueSlider <- renderUI({
    if(bools()[3]) {
      sliderInput(inputId = "s3", 
                          label = "Fatigue", 
                            min = 0, 
                            max = 1, 
                            value = 0.381, 
                            step = 0.001)
    }
  })
  
  output$shortofBreathSlider <- renderUI({
    if(bools()[4]) {
      sliderInput(inputId = "s4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.186, 
                          step = 0.001)
    }
  })
  
  output$soreThroatSlider <- renderUI({
    if(bools()[5]) {
       sliderInput(inputId = "s5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.139, 
                          step = 0.001)
    }
  })
  
  output$headacheSlider <- renderUI({
    if(bools()[6]) {
      sliderInput(inputId = "s6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.136, 
                          step = 0.001)
    }
  })
  
  output$chillsSlider <- renderUI({
    if(bools()[7]) {
      sliderInput(inputId = "s7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.114, 
                          step = 0.001)
    }
  })
  
  output$nauseaSlider <- renderUI({
    if(bools()[8]) {
      sliderInput(inputId = "s8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    }
  })
  
  output$congestionSlider <- renderUI({
    if(bools()[9]) {
      sliderInput(inputId = "s9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.048, 
                          step = 0.001)
    }
  })
  
  output$diarrheaSlider <- renderUI({
    if(bools()[10]) {
      sliderInput(inputId = "s10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.037, 
                          step = 0.001)
    }
  })

shinyApp(ui, server)
```