---
runtime: shiny
output: ioslides_presentation
---


```{r, include=FALSE}
library(shinydashboard)
library(shiny)
library(bayesrules)  # for the plotting functions
library(ggplot2)
```

```{r, include=FALSE}
header <- dashboardHeader(title = "COVID-19 Symptom Checker", titleWidth = 300)
```

```{r, include=FALSE}
sidebar <- dashboardSidebar(
  ## Sidebar content
    dashboardSidebar(
      sidebarMenu(
         menuItem("Welcome", tabName = "welcome", icon = icon("info")),  
        menuItem("Symptoms", tabName = "symptoms", icon = icon("thermometer-three-quarters")),
        menuItem("Symptom Probabilities", tabName = "covidprobs", icon = icon("dashboard")),
        menuItem("Disease Prevalence", tabName = "diseaseprev", icon = icon("dashboard")),
        menuItem("Results", tabName = "results", icon = icon("poll-h"))
        )
      )
)

```

```{r, include=FALSE}

body <- dashboardBody(tabItems(
  
  tabItem(tabName = "welcome",
          tags$h2("Welcome to a Naive Bayesian Model for COVID-19"),
          tags$p("Welcome to a Naive Bayesian Model for COVID-19. In this SHINY app, there are two main features. In the symptoms tab you can check the box of which symptoms you are experiencing. The results tab will then tell you the probability that you have COVID-19, the probability that you have the flu, and the probability that you have neither. In the 'Probabilities' tabs you can adjust the probabilities for each symptom. We made assumptions about default probabilities using data from the following sources:"),
          tags$p(tags$a(href="https://www.cdc.gov/flu/symptoms/coldflu.htm", "CDC")),
          tags$p(tags$a(href="https://www.who.int/docs/default-source/coronaviruse/who-china-joint-mission-on-covid-19-final-report.pdf", "WHO")),
          
tags$p("Since this is a Naive Bayes model we needed to make some assumptions. Our model assumes independence among each symptom and it assumes independence between the flu, COVID-19 and neither. We also limited the number of symptom in our model. We choose 10 symptoms because they are the most common and we were able to find the most information about these symptoms in order to assign default probabilites. Finally, although we did have reaserch for each symptom we made some assumptions about the probabilities for each symptom. We hoped to remedy that to some extent by allowing users to change the probabilities for each symptom in the 'Symptom Probabilities' tab."), 
          
          tags$div(
            tags$b("Theory"),
            tags$h4(withMathJax("$$P(C) + P(F) + P(N) = 1$$")),
            tags$h4(withMathJax("$$P(C|S_{1},S_{2},...,S_{n}) \\propto c = P(C)*\\prod_{i=1}^{n}P(S_{i}|C)$$")),
            tags$h4(withMathJax("$$P(F|S_{1},S_{2},...,S_{n}) \\propto f = P(F)*\\prod_{i=1}^{n}P(S_{i}|F)$$")),
            tags$h4(withMathJax("$$P(N|S_{1},S_{2},...,S_{n}) \\propto n = P(N)*\\prod_{i=1}^{n}P(S_{i}|N)$$")),
            tags$p("Then, we have: "),
            tags$h4(withMathJax("$$P(C|S_{1},S_{2},...,S_{n}) = \\frac{c}{c+f+n}$$")),
            tags$h4(withMathJax("$$P(F|S_{1},S_{2},...,S_{n}) = \\frac{f}{c+f+n}$$")),
            tags$h4(withMathJax("$$P(N|S_{1},S_{2},...,S_{n}) = \\frac{n}{c+f+n}$$")),
            tags$p(withMathJax("Where P(C) = Probability of COVID-19, P(F) = Probability of Flu, and P(N) = Probability of neither. P(C) and P(F) are estimates of the proportions of people with each respective disease at a given time. Each S represents a different symptom that a person may experience with COVID-19. $$P(S_{i}|C)$$ is the probability of having symptom i when a person has COVID-19. This applies to $$P(S_{i}|F)$$ and $$P(S_{i}|N)$$ with the flu and neither, respectively."))
          ),
          
          tags$div(
            HTML("<b>NOTICE:</b> This app should not be used for diagnosis. We used Naive Bayesian Statistics for our model so many assumptions were made in the creation of this app. If you think that you have COVID-19, you should get tested immediately and stay quarantined until you are recovered."))),
        
  
  
  #First tab content
  tabItem(tabName = "symptoms",
            fluidRow(
              box(title = "Instructions:", "Check all of your symptoms. Once finished, either adjust the probabilites in the following two tabs (though they have already been set to approximate values) or proceed to the results tab for the probabilites of each disease.", width = 12)),
          fluidRow(
              box(
                checkboxInput(inputId = "isFever", 
                              label = "Fever",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isDryCough", 
                              label = "Dry Cough",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isFatigue", 
                              label = "Fatigue",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isShortBreath", 
                              label = "Shortness of Breath",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isSoreThroat", 
                              label = "Sore Throat",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isHeadache", 
                              label = "Headache",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isChills", 
                              label = "Chills",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isNausea", 
                              label = "Nausea",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isCongestion", 
                              label = "Congestion",
                              value = FALSE)
              ),
              box(
                checkboxInput(inputId = "isDiarrhea", 
                              label = "Diarrhea",
                              value = FALSE)
              )
              # , 
              # box(
              #   checkboxInput(inputId = "isJointAche", 
              #                 label = "Joint Ache",
              #                 value = FALSE)
              # )
            )
          ),
  
  # Second tab content
  tabItem(tabName = "covidprobs",
          fluidRow(
            box(title = "Instructions:", "Here, you can adjust the probabilites of each symptom given each disease. We set the initial values based on preliminary research, but these values can change as research develops.", width = 12
            )),
          fluidRow(
            box(title = "COVID-19 Probabilities",
                uiOutput("feversliderC"),
                uiOutput("dryCoughSliderC"),
                uiOutput("fatigueSliderC"),
                uiOutput("shortofBreathSliderC"),
                uiOutput("soreThroatSliderC"),
                uiOutput("headacheSliderC"),
                uiOutput("chillsSliderC"),
                uiOutput("nauseaSliderC"),
                uiOutput("congestionSliderC"),
                uiOutput("diarrheaSliderC")
                ),
            box(title = "Flu Probabilities",
                uiOutput("feversliderF"),
                uiOutput("dryCoughSliderF"),
                uiOutput("fatigueSliderF"),
                uiOutput("shortofBreathSliderF"),
                uiOutput("soreThroatSliderF"),
                uiOutput("headacheSliderF"),
                uiOutput("chillsSliderF"),
                uiOutput("nauseaSliderF"),
                uiOutput("congestionSliderF"),
                uiOutput("diarrheaSliderF")
                ),
            box(title = "Neither Probabilites",
                uiOutput("feversliderS"),
                uiOutput("dryCoughSliderS"),
                uiOutput("fatigueSliderS"),
                uiOutput("shortofBreathSliderS"),
                uiOutput("soreThroatSliderS"),
                uiOutput("headacheSliderS"),
                uiOutput("chillsSliderS"),
                uiOutput("nauseaSliderS"),
                uiOutput("congestionSliderS"),
                uiOutput("diarrheaSliderS")
                )
            )
          ),
  
  tabItem(tabName = "diseaseprev",
          fluidRow(
            box(title = "Instructions:", "On this page, you can adjust the probabilities to reflect the infection rate of each disease in your population. This tab can help to account for seasonality including the time of year or the geographical location that are relevant when taking this test. Here you can adjust the probability of having COVID-19 (P(C)) and the Flu (P(F)). The probability of neither (P(N)) is calculated by subtracting P(C) and P(F) from 1.", width = 12)),
           fluidRow(
            box(
              sliderInput(inputId = "covidPrev", 
                          label = "COVID-19 Infection Rate", 
                          min = 0, 
                          max = 1, 
                          value = 0.002, 
                          step = 0.001),
              sliderInput(inputId = "fluPrev", 
                          label = "Flu Infection Rate", 
                          min = 0, 
                          max = 1, 
                          value = 0.01, 
                          step = 0.001)
            )
          )
          ),
  
  tabItem(tabName = "results",
    fluidRow(
      box(
                title = "Results",
                h3("Probability of COVID-19 = ", textOutput("resultC", container = span)),
                h3("Probability of flu = ", textOutput("resultF", container = span)),
                h3("Probability of neither = ", textOutput("resultN", container = span))
                ),
    fluidRow(
      box(h3("You most likely have:", textOutput("most_likely", container = span))),
      box(plotOutput("plot1", width = "100%"))
    ),
    box(title = "WARNING:", "The results from this app should not be used for diagnosis. We used Naive Bayesian Statistics for our model so many assumptions were made in the creation of this app. If you think that you have COVID-19, you should get tested immediately and stay quarantined until you are recovered.", width = 12)
  )
  )
  
))

```


```{r echo=FALSE}
ui <- dashboardPage(header, sidebar, body)


server <- function(input, output) {
  
  bools <- reactive({
      c(input$isFever, input$isDryCough, input$isFatigue, input$isShortBreath, input$isSoreThroat, input$isHeadache, input$isChills, input$isNausea, input$isCongestion, input$isDiarrhea)
    })
  
  # includes values only for the symptoms checked
  c_vals <- reactive({
    c(input$c1, input$c2, input$c3, input$c4, input$c5, input$c6, input$c7, input$c8, input$c9, input$c10)
  })
  
  f_vals <- reactive({
    c(input$f1, input$f2, input$f3, input$f4, input$f5, input$f6, input$f7, input$f8, input$f9, input$f10)
  })
  
  s_vals <- reactive({
    c(input$s1, input$s2, input$s3, input$s4, input$s5, input$s6, input$s7, input$s8, input$s9, input$s10)
  })
  
  covidPrevious <- reactive({ input$covidPrev })
  fluPrevious <- reactive({ input$fluPrev })
  
  results <- reactive({
    c_prop <- prod(c_vals()) * covidPrevious()
    f_prop <- prod(f_vals()) * fluPrevious()
    n_prop <- prod(s_vals()) * (1 - covidPrevious() - fluPrevious())
    
    covid <- c_prop/(c_prop+f_prop+n_prop)
    flu <- f_prop/(c_prop+f_prop+n_prop)
    neither <- n_prop/(c_prop+f_prop+n_prop)
    c(covid, flu, neither)
  })
  
  output$resultC <- renderText({
    results()[1]
  })
  
  output$resultF <- renderText({
    results()[2]
  })
  
  output$resultN <- renderText({
    results()[3]
  })
  
  
  output$most_likely <- renderText({
    final_prob <- ""
    if(results()[1] > results()[2] & results()[1] > results()[3]){
      final_prob <- "COVID-19"
    } else if (results()[2] > results()[3]) {
      final_prob <- "Flu"
    } else {
      final_prob <- "Neither"
    }
  })
  
  output$plot1 <- renderPlot(
    barplot(results(), names.arg=c("COVID-19", "Flu", "Neither"))
  )
  
  
# Sliders for covid
  output$feversliderC  <- renderUI({
    if(bools()[1]) {
      sliderInput(inputId = "c1", 
                            label = "Fever:", 
                            min = 0, 
                            max = 1, 
                            value = 0.879, 
                            step = 0.001)
    }
  })
  
  output$dryCoughSliderC <- renderUI({
    if(bools()[2]) {
      sliderInput(inputId = "c2", 
                            label = "Dry Cough:", 
                            min = 0, 
                            max = 1, 
                            value = 0.677, 
                            step = 0.001)
    }
  })
  
  output$fatigueSliderC <- renderUI({
    if(bools()[3]) {
      sliderInput(inputId = "c3", 
                          label = "Fatigue", 
                            min = 0, 
                            max = 1, 
                            value = 0.381, 
                            step = 0.001)
    }
  })
  
  output$shortofBreathSliderC <- renderUI({
    if(bools()[4]) {
      sliderInput(inputId = "c4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.186, 
                          step = 0.001)
    }
  })
  
  output$soreThroatSliderC <- renderUI({
    if(bools()[5]) {
       sliderInput(inputId = "c5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.139, 
                          step = 0.001)
    }
  })
  
  output$headacheSliderC <- renderUI({
    if(bools()[6]) {
      sliderInput(inputId = "c6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.136, 
                          step = 0.001)
    }
  })
  
  output$chillsSliderC <- renderUI({
    if(bools()[7]) {
      sliderInput(inputId = "c7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.114, 
                          step = 0.001)
    }
  })
  
  output$nauseaSliderC <- renderUI({
    if(bools()[8]) {
      sliderInput(inputId = "c8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    }
  })
  
  output$congestionSliderC <- renderUI({
    if(bools()[9]) {
      sliderInput(inputId = "c9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.048, 
                          step = 0.001)
    }
  })
  
  output$diarrheaSliderC <- renderUI({
    if(bools()[10]) {
      sliderInput(inputId = "c10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.037, 
                          step = 0.001)
    }
  })
  
# Sliders for flu
  output$feversliderF  <- renderUI({
    if(bools()[1]) {
      sliderInput(inputId = "f1", 
                            label = "Fever:", 
                            min = 0, 
                            max = 1, 
                            value = 0.68, 
                            step = 0.001)
    }
  })
  
  output$dryCoughSliderF <- renderUI({
    if(bools()[2]) {
      sliderInput(inputId = "f2", 
                            label = "Dry Cough:", 
                            min = 0, 
                            max = 1, 
                            value = 0.93, 
                            step = 0.001)
    }
  })
  
  output$fatigueSliderF <- renderUI({
    if(bools()[3]) {
      sliderInput(inputId = "f3", 
                          label = "Fatigue", 
                            min = 0, 
                            max = 1, 
                            value = 0.94, 
                            step = 0.001)
    }
  })
  
  output$shortofBreathSliderF <- renderUI({
    if(bools()[4]) {
      sliderInput(inputId = "f4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001)
    }
  })
  
  output$soreThroatSliderF <- renderUI({
    if(bools()[5]) {
       sliderInput(inputId = "f5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001)
    }
  })
  
  output$headacheSliderF <- renderUI({
    if(bools()[6]) {
      sliderInput(inputId = "f6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001)
    }
  })
  
  output$chillsSliderF <- renderUI({
    if(bools()[7]) {
      sliderInput(inputId = "f7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.5, 
                          step = 0.001)
    }
  })
  
  output$nauseaSliderF <- renderUI({
    if(bools()[8]) {
      sliderInput(inputId = "f8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001)
    }
  })
  
  output$congestionSliderF <- renderUI({
    if(bools()[9]) {
      sliderInput(inputId = "f9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.5, 
                          step = 0.001)
    }
  })
  
  output$diarrheaSliderF <- renderUI({
    if(bools()[10]) {
      sliderInput(inputId = "f10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    }
  })

# Sliders for basic symptoms
  output$feversliderS  <- renderUI({
    if(bools()[1]) {
      sliderInput(inputId = "s1", 
                            label = "Fever:", 
                            min = 0, 
                            max = 1, 
                            value = 0.01, 
                            step = 0.001)
    }
  })
  
  output$dryCoughSliderS <- renderUI({
    if(bools()[2]) {
      sliderInput(inputId = "s2", 
                            label = "Dry Cough:", 
                            min = 0, 
                            max = 1, 
                            value = 0.05, 
                            step = 0.001)
    }
  })
  
  output$fatigueSliderS <- renderUI({
    if(bools()[3]) {
      sliderInput(inputId = "s3", 
                          label = "Fatigue", 
                            min = 0, 
                            max = 1, 
                            value = 0.1, 
                            step = 0.001)
    }
  })
  
  output$shortofBreathSliderS <- renderUI({
    if(bools()[4]) {
      sliderInput(inputId = "s4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.03, 
                          step = 0.001)
    }
  })
  
  output$soreThroatSliderS <- renderUI({
    if(bools()[5]) {
       sliderInput(inputId = "s5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    }
  })
  
  output$headacheSliderS <- renderUI({
    if(bools()[6]) {
      sliderInput(inputId = "s6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.1, 
                          step = 0.001)
    }
  })
  
  output$chillsSliderS <- renderUI({
    if(bools()[7]) {
      sliderInput(inputId = "s7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.01, 
                          step = 0.001)
    }
  })
  
  output$nauseaSliderS <- renderUI({
    if(bools()[8]) {
      sliderInput(inputId = "s8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    }
  })

  output$congestionSliderS <- renderUI({
    if(bools()[9]) {
      sliderInput(inputId = "s9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001)
    }
  })
  
  output$diarrheaSliderS <- renderUI({
    if(bools()[10]) {
      sliderInput(inputId = "s10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.001, 
                          step = 0.001)
    }
  })
}

shinyApp(ui, server)
```



