---
title: "Dashboard"
author: "Camilla Bendetti, Rock Pang, Jane Roarty"
date: "4/24/2020"
output: html_document
---

```{r cache=TRUE}
library(shinydashboard)
library(shiny)
library(bayesrules)  # for the plotting functions
library(ggplot2)
```



```{r}
header <- dashboardHeader(title = "Covid-19 Symptom Checker")

sidebar <- dashboardSidebar(
  ## Sidebar content
    dashboardSidebar(
      sidebarMenu(
         menuItem("Model 1", tabName = "model1", icon = icon("dashboard")),
        menuItem("Model 2", tabName = "model2", icon = icon("dashboard"))
        ),
      sliderInput(inputId = "fever", 
                          label = "Fever:", 
                          min = 0, 
                          max = 1, 
                          value = 0.879, 
                          step = 0.001),
      sliderInput(inputId = "cough", 
                          label = "Dry Cough:", 
                          min = 0, 
                          max = 1, 
                          value = 0.677, 
                          step = 0.001),
              sliderInput(inputId = "fatigue", 
                          label = "Fatigue", 
                          min = 0, 
                          max = 1, 
                          value = 0.381, 
                          step = 0.001),
              sliderInput(inputId = "breath", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.186, 
                          step = 0.001),
              sliderInput(inputId = "throat", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.139, 
                          step = 0.001),
              sliderInput(inputId = "headache", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.136, 
                          step = 0.001),
              sliderInput(inputId = "chills", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.114, 
                          step = 0.001),
              sliderInput(inputId = "nausea", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
              sliderInput(inputId = "congestion", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.048, 
                          step = 0.001),
              sliderInput(inputId = "diarrhea", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.037, 
                          step = 0.001)
      
      
  )
)

body <- dashboardBody(tabItems(
  
  #First tab content
  tabItem(tabName = "model1",
          h2("content")
          ),
  
  # Second tab content
  tabItem(tabName = "model2",
          fluidRow(
            box(
              title = "Symptoms",
              sliderInput(inputId = "s1", 
                          label = "Fever:", 
                          min = 0, 
                          max = 1, 
                          value = 0.879, 
                          step = 0.001),
              sliderInput(inputId = "s2", 
                          label = "Dry Cough:", 
                          min = 0, 
                          max = 1, 
                          value = 0.677, 
                          step = 0.001),
              sliderInput(inputId = "s3", 
                          label = "Fatigue", 
                          min = 0, 
                          max = 1, 
                          value = 0.381, 
                          step = 0.001),
              sliderInput(inputId = "s4", 
                          label = "Shortness of Breath", 
                          min = 0, 
                          max = 1, 
                          value = 0.186, 
                          step = 0.001),
              sliderInput(inputId = "s5", 
                          label = "Sore Throat", 
                          min = 0, 
                          max = 1, 
                          value = 0.139, 
                          step = 0.001),
              sliderInput(inputId = "s6", 
                          label = "Headache", 
                          min = 0, 
                          max = 1, 
                          value = 0.136, 
                          step = 0.001),
              sliderInput(inputId = "s7", 
                          label = "Chills", 
                          min = 0, 
                          max = 1, 
                          value = 0.114, 
                          step = 0.001),
              sliderInput(inputId = "s8", 
                          label = "Nausea or Vomiting", 
                          min = 0, 
                          max = 1, 
                          value = 0.05, 
                          step = 0.001),
              sliderInput(inputId = "s9", 
                          label = "Congestion", 
                          min = 0, 
                          max = 1, 
                          value = 0.048, 
                          step = 0.001),
              sliderInput(inputId = "s10", 
                          label = "Diarrhea", 
                          min = 0, 
                          max = 1, 
                          value = 0.037, 
                          step = 0.001)
            ),
            
            box(
              title = "Results",
              tableOutput("priorTable"),
              h3("Probability of covid-19 = ", textOutput("result", container = span))
            )
          )
          )
  
))


ui <- dashboardPage(header, sidebar, body)


server <- function(input, output) {
  
  output$priorTable <- renderTable({
    df <- data.frame(S1 = c(input$s1),
                   S2 = c(input$s2),
                   S3 = c(input$s3),
                   S4 = c(input$s4),
                   S5 = c(input$s5),
                   S6 = c(input$s6),
                   S7 = c(input$s7),
                   S8 = c(input$s8),
                   S9 = c(input$s9),
                   S10 = c(input$s10)
                   )
    
    df
  })
  
  output$result <- renderText({
    covid <- input$s1 * input$s2 * input$s3 * input$s4 * input$s5 * input$s6 * input$s7 * input$s8 * input$s9 * input$s10 * 0.002
    covid
  })
}

shinyApp(ui, server)
```








